### ISSUE TITLE
Cann't denoise on my dataset

### ISSUE THREAD

**Issue by Four-Fire** [StanfordMIMI/DDM2#1]
Hi, I wanted to denoise on my dataset but it failed. I have found that this project doesn't include any model that have trained well, Is that true?

**Comment by tiangexiang** [comment]
Hi, our model is designed to be dataset-specific, so you need to train one model for one dataset. There is no pre-trained model that can be used for multiple different datasets.
To understand why you failed to denoise on your dataset, can you please double-check that your dataset is indeed in the same format (e.g 4 dimensions) as the datasets in our examples?
Thanks!

**Comment by Four-Fire** [comment]
OK, I will have a try. 
Thank you a lot!
