### ISSUE TITLE
2d-image

### ISSUE THREAD

**Issue by Koid217** [StanfordMIMI/DDM2#13]
Hello, I was wondering if this can be used for 2D images

**Comment by tiangexiang** [comment]
Theoretically yes! But you have to have multiple noisy observations of the same 2D image, which will give you a 3D volume of size: T (the number of observations) x W (width) x H (height).

**Comment by Koid217** [comment]
Could T be 2 (for example, images with noise and images without noise)?

**Comment by tiangexiang** [comment]
Unfortunately, I don't think T=2 can work as expected. DDM2 roughly requires T>=5 to be functional. Also, in our experiments, we sifted out clean data and didn't use them for training so I don't think including the clean image is a good idea.

**Comment by Koid217** [comment]
Thank you so much for your reply and advice！
